# Generated by Django 4.2.7 on 2023-12-06 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Breed', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=255)),
                ('age', models.IntegerField()),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=255)),
                ('color', models.CharField(choices=[('White/light', 'White/light'), ('Black/dark', 'Black/dark'), ('Colorless', 'Colorless'), ('Bicolor', 'Bicolor'), ('Multi-color', 'Multi-color')], max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('location', models.CharField(choices=[('Ontario', 'Ontario'), ('British Columbia', 'British Columbia'), ('Quebec', 'Quebec'), ('Alberta', 'Alberta'), ('Nova Scotia', 'Nova Scotia'), ('Saskat', 'Saskat')], max_length=255)),
                ('medical_history', models.CharField(max_length=255)),
                ('special_needs', models.CharField(max_length=255)),
                ('behaviour_description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('Adopted', 'Adopted'), ('Withdrawed', 'Withdrawed'), ('Available', 'Available'), ('Pending', 'Pending')], default='Pending', max_length=255)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='account.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('household_info', models.CharField(max_length=255)),
                ('pet_history', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Withdrawn', 'Withdrawn'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='account.seeker')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='pet.pet')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='account.shelter')),
            ],
        ),
    ]
