# Generated by Django 4.2.7 on 2023-12-06 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField()),
                ('object_id1', models.PositiveIntegerField()),
                ('content_type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type1', to='contenttypes.contenttype')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_lst', to='account.shelter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id2', models.PositiveIntegerField()),
                ('content_type2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type2', to='contenttypes.contenttype')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_lst', to='comment.review')),
            ],
            options={
                'verbose_name': 'reply',
                'verbose_name_plural': 'replies',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('object_id3', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.application')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.contenttype')),
                ('content_type3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type3', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
